### ISSUE TITLE
You can place towers behind the shop, but once you click away the shop re-appears and you can no longer click on the tower

### ISSUE THREAD

**Issue by ChaseOB** [gabrieltm9/Galactic-Gauntlet-Remastered#5]

**Comment by ChaseOB** [comment]
Sometimes when trying to buy a tower it will be placed behind the shop automatically, and sometimes you become stuck on that tower forever as hitting escape and q wont de-select/sell it

**Comment by gabrieltm9** [comment]
There are 2 options here. Make it so you cant place towers in the UI areas, or make the UI toggleable. I have for now settled for the latter, with Z toggling UI
